### ISSUE TITLE
Adding gradle build examples

### ISSUE THREAD

**Issue by mrwilson** [jvm-repo-rebuild/reproducible-central#6]
Hi,

I recently merged a set of PRs to get [Mockito3](https://github.com/mockito/mockito/pull/1892) and [JUnit5](https://github.com/junit-team/junit5/pull/2217) mostly building reproducibly under Gradle (with the exception of the javadocs jars).

There are some interesting edge-cases around an old version of Gradle's OSGi plugin which makes manual intervention necessary to maintain reproducibility.

What's the best way to add information about these, just raise a PR?

Thanks,

Alex

**Comment by hboutemy** [comment]
yes, PRs welcome
we'll need to start with buildpsec
then an update to rebuild.sh to be able to rebuild against buildspec
then an update to be able to check that the rebuild matches the reference build on central
perhaps we'll need to do the work in multiple steps, in a separate branch
let's start and work step by step: I'm glad to be able to work on sbt rebuilds in #4 and now on Gradle rebuilds

**Comment by hboutemy** [comment]
I just added in 7a82da531cc4100142bb1ff0a150fa7784118584 a new tool=gradle option in buildspec to prepare support for Gradle

**Comment by mrwilson** [comment]
Thanks for the reply.

I'm happy to add the buildspecs and have a go at building functionality into `rebuild.sh` for gradle.

**Comment by hboutemy** [comment]
thank you for your help: greatly appreciated
I'll create a branch and merge improvements step by step

**Comment by hboutemy** [comment]
gradle branch created https://github.com/jvm-repo-rebuild/reproducible-central/tree/gradle

you can have a look at the first step I did on sbt https://github.com/jvm-repo-rebuild/reproducible-central/tree/sbt and the discussion on improvements required to go beyond in #4

**Comment by hboutemy** [comment]
@mrwilson are you still interested in working on this?

**Comment by cimi** [comment]
👋 Hi there! I'm also interested in having reproducible builds for a project that uses gradle and it would be great to validate them here. I have a couple of questions about the preferred way to run gradle.

I was reading `rebuild.sh` and I saw in the maven function that, depending on the desired JDK version, we choose a docker image with a certain maven version.

Projects that build with gradle typically include [a Gradle wrapper](https://docs.gradle.org/current/userguide/gradle_wrapper.html) which ensures that a specific version of gradle is downloaded at build time when not present and uses that to build. Given this, does it make sense to just use a debian image with the desired JDK installed when the build tool is set to `gradle`?

And secondly, are there any plans to allow user to select the docker image they want to build on? The project I'm looking at already has a Dockerfile it uses to build in CI, it would be easiest if we could just reference that.

Thanks! 😃

**Comment by hboutemy** [comment]
it's really nice to see interest: thank you.

you're right, using Gradle Wrapper make perfect sense, and is a good simplification: let's go for that approach

on selecting a Docker image: the idea is that rebuild.sh has to work with parameters provided in buildspec
any convention can be defined: the only consequence of defining a convention is that it costs code in rebuild.sh, then it is a good idea only if it is sufficiently generic to be reused across many buildspecs.

That's why for example only supporting Gradle Wrapper make sense: the vast majority of projects use Gradle Wrapper
But only supporting Maven Wrapper would not make sense: it's not so widely used.

Then just think at how code added to rebuild.sh will be useful for more than 1 buildspec

Honestly, now that you found that using Gradle Wrapper as main option is the right approach, I feel that rebuilding many projects should be easy (I suppose only advanced ones have more prerequisites on a dedicate image)
The key aspect that is still missing to me is the way to compare the local build against the reference build published to Maven Central = what `artifact:compare` does in the Maven case
Do you have an idea?

**Comment by hboutemy** [comment]
> do you have an idea

given Gradle seems to always generate a `.module` file that lists every file, with a quite simple json format, we can probably create a simple tool that uses that input

**Comment by hboutemy** [comment]
yo just gave me another (better) idea: instead of coding a Gradle-specific compare tool, we could "deploy to a staging repository" and compare the staging repository content to what is available in Maven Central
this could work for Gradle, but also Maven (dropping the `artifact:compare` use for this more transparent script), or sbt
At build level, it only requires to be able to deploy to a staging directory: I know how to do that with Maven https://maven.apache.org/plugins/maven-deploy-plugin/examples/deploy-network-issues.html#Deploying_to_a_Local_Directory , if someone can show me how to do that for Gradle, please...

**Comment by hboutemy** [comment]
I just added a new `gradle` branch https://github.com/jvm-repo-rebuild/reproducible-central/tree/gradle
you can `./rebuild.sh wip/mockito-4.4.0.buildspec` to see the first build, that uses proposed strategy: just use JDK base image and gradlew
The build fails, but I don't know how to fix: feedback welcome

**Comment by cimi** [comment]
> instead of coding a Gradle-specific compare tool, we could "deploy to a staging repository" and compare the staging repository content to what is available in Maven Central

:+1: Deploying to the local Maven repo and comparing the artefacts from there makes sense to me. I've never done this before, so I looked at the documentation and found that the [`maven-publish` gradle plugin](https://docs.gradle.org/current/userguide/publishing_maven.html#publishing_maven:install) has a default task `publishToMavenLocal`. This is an official plugin published by the gradle authors.

Projects that use this plugin to publish its artefacts to central should publish the same artifacts to the local repository when running `./gradlew publishToMavenLocal`. I tried this in the project I'm interested in and it worked. 

> on selecting a Docker image: the idea is that rebuild.sh has to work with parameters provided in buildspec
> any convention can be defined: the only consequence of defining a convention is that it costs code in rebuild.sh, then it is a good idea only if it is sufficiently generic to be reused across many buildspecs.

I understand and it makes sense to want to restrict which docker images are executed - I guess this is the reason the docker image is not an option in `.buildspec`. Unfortunately this won't work for the project I want to integrate, it needs to have both JDK8 and JDK11 available at build time and it needs the two JDK directories set in environment variables.

**Comment by hboutemy** [comment]
updated branch https://github.com/jvm-repo-rebuild/reproducible-central/tree/gradle
now, `./rebuild.sh wip/mockito-4.4.0.buildspec` does not fail
but I don't know where to find the output: please help

**Comment by hboutemy** [comment]
@mrwilson @cimi as you can see, I added code to compare local rebuild against reference from central
mockito rebuild result are visible in [content/org/mockito/mockito-core/README.md](content/org/mockito/mockito-core/README.md)
you can rebuild locally with `./rebuild.sh content/org/mockito/mockito-core/mockito-4.4.0.buildspec`

as you can see, some reproducibility issues are stupid group write flag difference
but there are also other difference in other aspects

if you manage to get a better result, don't hesitate to share improvements in buildspec or rebuild.sh

**Comment by jskov** [comment]
Ah! Pooh! It can only extract text, not state&colors.
